### ISSUE TITLE
Errors in Interaction 2 of Scenario A version 3.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#175]
It seems that json is not validated against the schema. Is this true?
The following error should not validate OK.
json has a property paper that doesn't exist in the schema. The property in the schema is named paperAndBoard.

To catch also other error that might exist, I propose that the json should be validated against the schema for all interactions before the new release is published.

Property sizetype should be removed from property basisWeight when uom=GramsPerSquareMeter.

The width of the reel in paper should be changed to from 787 to 875 Millimeter to match the area of the reel in the delivery note (length=4000 m, Area=3500 m2)

Please also correct the errors for property paper and basisWeight and width within paper in other interactions.

**Scenario A interaction 2 description**
2. _Logistics supplier_ **requests** to get details of the one specific active _supplier-order_ from _supplier_.
_Logistics supplier_ **receives** details of this _supplier-order_, including the number of _packages_.
In this scenario, there are 10 _packages_.

There are no packages in the details of the supplier-order. Change _packages_ to _reels_ in this description.

**Comment by patricekrakow** [comment]
1. There was actually an error within the schemas when defining the `sellerProduct:`. The `sellerProduct.properties.paper` was changed to `sellerProduct.properties.paperAndBoard`, but the value of `sellerProduct.allOf[1].oneOf[0].required[0]` was still `paper` and not `paperAndBoard`. When changed the error was captured by `ajv` and the errors have been corrected in the instances.

2. The script `validate.cmd` has been added to `/tools/`. (still working on it...)

3. It is not possible to condition a property based on a particular value taken by another property.

4. I have changed `"value": 787` to `"value: 875` in
   - `\3.0.0\mock\GW04&BW04.get-logistic-delivery-notes-logisticDeliveryNoteId.response.json` (1 occurrence)
   - `\3.0.0\mock\GW04&BW04.get-logistic-delivery-notes-logisticDeliveryNoteId.response.json` (1 occurrence)
   - `\3.0.0\mock\papiNet.PACT.json` (4 occurrences)
   - `3.0.0\paper-board-pulp-warehouse-logistics.md`  (4 occurrences)

5.

**Comment by patricekrakow** [comment]
Done, see commit [e601f69](https://github.com/papinet/papiNet-API/commit/e601f690ae5e033fc1f67e0f0bc7577e07a85962).

@larsolofsson please close this issue if you agree with the updates.

**Comment by larsolofsson** [comment]
Property sizetype is still not removed from property basisWeight, when uom=GramsPerSquareMeter.

**Comment by patricekrakow** [comment]
3. OK, I did not understand that you were talking about the instances. I have removed `"sizeType": "24x36"` from
   - `\3.0.0\mock\GW02&BW02.get-supplier-orders-supplierOrderId.response.json` (1 occurrence)
   - `\3.0.0\mock\GW04&BW04.get-logistic-delivery-notes-logisticDeliveryNoteId.response.json` (1 occurrence)
   - `\3.0.0\paper-board-pulp-warehouse-logistics.md` (4 occurrences)
   - `\3.0.0\mock\papiNet.PACT.json` (4 occurrences)
